import type { ArchitectureGraph } from "../graph/types";

export type ArtifactFile = {
  filename: string;
  language: string;
  content: string;
  description: string;
};

export function generateImplementationArtifacts(graph: ArchitectureGraph): ArtifactFile[] {
  const nodes = graph.nodes;
  const dbNodes = nodes.filter((n) => n.type === "database");
  const serviceNodes = nodes.filter((n) => n.type === "microservice");
  const cacheNodes = nodes.filter((n) => n.type === "cache");
  const queueNodes = nodes.filter((n) => n.type === "queue");

  // 1. Docker Compose
  const dockerServices = nodes.map((n) => {
    if (n.type === "database") {
      return `  ${n.id.toLowerCase()}:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${n.id.toLowerCase()}_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: \${DB_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data`;
    }
    if (n.type === "cache") {
      return `  ${n.id.toLowerCase()}:
    image: redis:7-alpine
    ports:
      - "6379:6379"`;
    }
    if (n.type === "queue") {
      return `  ${n.id.toLowerCase()}:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${n.id.toLowerCase()}:9092`;
    }
    return `  ${n.id.toLowerCase()}:
    build:
      context: ./${n.id.toLowerCase()}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production`;
  }).join("\n\n");

  const dockerCompose = `version: '3.8'

services:
${dockerServices}

volumes:
  pgdata:
`;

  // 2. SQL Schema DDL
  const sqlTables = dbNodes.length > 0
    ? dbNodes.map((db) => `-- SQL Schema for ${db.name}
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ${db.id.toLowerCase()}_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    payload JSONB NOT NULL,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_${db.id.toLowerCase()}_user ON ${db.id.toLowerCase()}_records(user_id);
`).join("\n\n")
    : `-- Standard Relational Persistence DDL
CREATE TABLE IF NOT EXISTS system_entities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);`;

  // 3. OpenAPI 3.0 Spec
  const openApi = JSON.stringify(
    {
      openapi: "3.0.3",
      info: {
        title: `${graph.title} API Specification`,
        version: "1.0.0",
        description: `Production API spec generated by Arqen AI for ${graph.title}.`,
      },
      paths: {
        "/api/v1/health": {
          get: {
            summary: "System Health Check",
            responses: { "200": { description: "Service Operational" } },
          },
        },
        ...Object.fromEntries(
          serviceNodes.map((s) => [
            `/api/v1/${s.id.toLowerCase()}`,
            {
              get: {
                summary: `Execute Query on ${s.name}`,
                responses: { "200": { description: "Successful response payload" } },
              },
              post: {
                summary: `Process Action on ${s.name}`,
                responses: { "201": { description: "Resource Created" } },
              },
            },
          ])
        ),
      },
    },
    null,
    2
  );

  // 4. Kubernetes Manifests
  const k8sManifests = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: arqen-app-deployment
  labels:
    app: ${graph.title.toLowerCase().replace(/[^a-z0-9]/g, "-")}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${graph.title.toLowerCase().replace(/[^a-z0-9]/g, "-")}
  template:
    metadata:
      labels:
        app: ${graph.title.toLowerCase().replace(/[^a-z0-9]/g, "-")}
    spec:
      containers:
      - name: main-api
        image: arqen/${graph.title.toLowerCase().replace(/[^a-z0-9]/g, "-")}:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: arqen-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ${graph.title.toLowerCase().replace(/[^a-z0-9]/g, "-")}
`;

  // 5. System README.md
  const readme = `# ${graph.title}

> Synthesized and analyzed by **Arqen AI Architecture Engine**.

## Architecture Overview
${graph.nodes.length} Components | ${graph.edges.length} Dependencies | Type: ${graph.diagramType.toUpperCase()}

### Component Inventory
${nodes.map((n) => `- **${n.name}** (\`${n.type}\`): ${n.description}`).join("\n")}

## Quick Start
\`\`\`bash
# Launch multi-container environment
docker-compose up -d
\`\`\`
`;

  return [
    { filename: "docker-compose.yml", language: "yaml", content: dockerCompose, description: "Multi-container Docker Compose setup for local development." },
    { filename: "openapi.json", language: "json", content: openApi, description: "OpenAPI 3.0 REST API specification for core services." },
    { filename: "schema.sql", language: "sql", content: sqlTables, description: "PostgreSQL DDL relational database schema with indices." },
    { filename: "k8s-deployment.yaml", language: "yaml", content: k8sManifests, description: "Kubernetes production Deployment & Service manifests." },
    { filename: "README.md", language: "markdown", content: readme, description: "Technical system documentation & setup guide." },
  ];
}
